// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBezRwe6UibcpcJ31qt9aQ61DGCeKEmYpk',
    appId: '1:901261351739:web:edaa1b2095c06695a5f51e',
    messagingSenderId: '901261351739',
    projectId: 'godely-push-notification',
    authDomain: 'godely-push-notification.firebaseapp.com',
    storageBucket: 'godely-push-notification.firebasestorage.app',
    measurementId: 'G-YNE8366YNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31hl-t7Po86EN5lJXpSoHCxHslWMNlk4',
    appId: '1:901261351739:android:3e0f595147c92d7ea5f51e',
    messagingSenderId: '901261351739',
    projectId: 'godely-push-notification',
    storageBucket: 'godely-push-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhiesvfaAaKA8gPRm9ZEDzQvJn7xLrr58',
    appId: '1:901261351739:ios:f0b853e0f6786941a5f51e',
    messagingSenderId: '901261351739',
    projectId: 'godely-push-notification',
    storageBucket: 'godely-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.goDely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhiesvfaAaKA8gPRm9ZEDzQvJn7xLrr58',
    appId: '1:901261351739:ios:f0b853e0f6786941a5f51e',
    messagingSenderId: '901261351739',
    projectId: 'godely-push-notification',
    storageBucket: 'godely-push-notification.firebasestorage.app',
    iosBundleId: 'com.example.goDely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBezRwe6UibcpcJ31qt9aQ61DGCeKEmYpk',
    appId: '1:901261351739:web:02f3ebcf2c1aa7e0a5f51e',
    messagingSenderId: '901261351739',
    projectId: 'godely-push-notification',
    authDomain: 'godely-push-notification.firebaseapp.com',
    storageBucket: 'godely-push-notification.firebasestorage.app',
    measurementId: 'G-6RH8N31F55',
  );
}